name: "⬆️ UX Improve"
description: "UX 개선"
labels: ["Type: Improve UX :arrow_up:"]
body:
  - type: textarea
    attributes:
      label: ❓ 설명
      description: 어떤 종류의 UX 개선인지 설명해주세요.
      placeholder: CLS 개선, 로딩 처리 개선 등
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
